name: Working with OIDC

on:
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Uses a specific user's *identity token* as the value for JF_PASSWORD
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-jfrog-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
        with:
          oidc-provider-name: github-oidc-integration
          oidc-audience: jfrog-github

      - name: Test basic JF CLI Authn and Authz
        run: |
          curl -XGET -utomj@jfrog.com -p${{ steps.setup-jfrog-cli.outputs.oidc-token}}

